### ISSUE TITLE
Why a list of colored noise? + Technical questions

### ISSUE THREAD

**Issue by sparisi** [martius-lab/pink-noise-rl#1]
Hi, thanks for releasing the code, I find it very easy to use. 
I have a few question about the implementation + 2 technical questions. 

[Here](https://github.com/martius-lab/pink-noise-rl/blob/f935654fd19148b284579db32412c16838958e79/pink/sb3.py#L34) you use one colored process for each action dimension. Why not using one process of the same dimensionality of the action? 
I tried and the code still works if I pass one process of size n, so maybe there is some other reason why you do that. 

In the stable_baseline implementation, the action is sampled using `mean + std * noise`. If noise is white then it's a Gaussian policy and we can use the usual equations and methods to compute log-prob, KL, ... 
But if noise is colored, then I guess that log-prob cannot be computed as usual. Isn't this a problem? Because in practice log-prob is computed using stddev, but stddev is then multiplied by a colored noise, not a white noise. 

Finally, say I am using an off-policy algorithm. The behavior policy collects samples with the colored noise. When I compute log-probs for the target policy, should I use colored noise or white noise? 

Thanks!

**Comment by onnoeberhard** [comment]
Hi Simone, thanks for your detailed comments! To answer your questions:
1. The reason we implemented it like this is that it makes it very easy to use different colors for different action dimensions, and it works fine for low-dimensional action spaces. However, you are right that it is a bit confusing, as the most common application is to use a single color for all action dimensions. I have changed the implementation to reflect this in the new version 2.0.0 of the package (version bump because it introduces some breaking changes). Now you can just pass a single beta value, together with the action space dimensionality, and the noise is sampled in a vectorized manner, as you describe it. This should make it much faster in high-dimensional spaces.
2. In fact, this is not a problem. The action distributions (i.e. `pi(a_t | s_t)`) are still Gaussian at every time step, and in fact independent of the time step, as `p(eps_t) = N(eps_t | 0, 1)` for all t if `eps_{1:T}` is sampled from a Gaussian colored noise process (as is the case here), please see also Section A (esp. Fig. A.3) of our paper: https://openreview.net/forum?id=hQ9V5QN27eS
3. As long as the algorithm only relies on the Gaussian marginal probabilities `pi(a_t | s_t)`, there is no difference between white noise and colored noise, as `pi(a_t | s_t) = mu(s_t) + std(s_t) * p(eps_t) = mu(s_t) + std(s_t) * N(eps_t | 0, 1)` in both cases. Again, this is because the marginal distribution of the colored noise for a single time step is standard Gaussian. Only if the algorithm depends on a distribution over multiple actions at different time steps, then the correlation needs to be taken into account, which is what differentiates white noise and other colors.

I hope this helps and don't hesitate to reach out again if it is unclear!

-- Onno

**Comment by sparisi** [comment]
Hi Onno, thanks a lot for the detailed reply, I really appreciate it!
